### PR TITLE
fix: Xcode 15 doesn't like iphoneos

### PR DESCRIPTION
**Pull request by elihwyma**
What does this implement/fix? Explain your changes.
---------------------------------------------------
…

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** …

**Platform:** …

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

### CODE REVIEW

**Review by PoomSmart — APPROVED** [review]

**Comment by kirb** [comment]
This will need to be changed across all rootful tbds. 

By merging this I believe we’ll be breaking support for Xcode with only tbdv1 support (Xcode 7). I think tbdv2 (Xcode 8) when the `ios` keyword was introduced. Are we ok with that compromise? I guess we don’t support built-in linkables prior to Xcode 7 anyway, so pushing up the minimum isn’t a big deal.

**Comment by PoomSmart** [comment]
Maybe you can have a legacy branch for Theos altogether for those old Xcode versions.

**Comment by leptos-null** [comment]
Noting for tracking that this will fix (at least the main issue in) https://github.com/theos/theos/issues/742

~~I agree with kirb that this PR should change the `platform` fields in all `tbd`s in this repo.~~

edit: My mistake- `CydiaSubstrate` is the only `tbd` in this repo with `platform: iphoneos`. Both the default and `iphone/rootless` versions have this discrepancy though and both should be patched.

---

Personally believe that this trade-off makes sense: break support for 1 year worth of releases that are now over 7 years old, in favor of future support. 

> Maybe you can have a legacy branch for Theos altogether for those old Xcode versions.

Personally believe this is more trouble than it's worth

**Review by leptos-null — APPROVED** [review]
Looks good. From additional discussions, it sounds like we're is okay to drop Xcode 7 support for these files.

**Comment by kirb** [comment]
Can we get this updated on all other tbds?

(Also, for consideration in a separate PR, this means we can upgrade them all to a much newer tbd format.)

**Comment by elihwyma** [comment]
> Can we get this updated on all other tbds?
> 
> (Also, for consideration in a separate PR, this means we can upgrade them all to a much newer tbd format.)

:fishsticks:

**Comment by leptos-null** [comment]
@kirb I believe this PR covers all `tbd`s that were effected in this repo

```txt
elihwyma-lib git:patch-1 $ grep -r "iphoneos" .
Binary file ./Alderis.framework/Modules/Alderis.swiftmodule/arm64.swiftmodule matches
Binary file ./Alderis.framework/Modules/Alderis.swiftmodule/arm64e-apple-ios.swiftmodule matches
Binary file ./Alderis.framework/Modules/Alderis.swiftmodule/arm64-apple-ios.swiftmodule matches
Binary file ./Alderis.framework/Modules/Alderis.swiftmodule/arm64e.swiftmodule matches
./Opener.framework/Info.plist:	<string>iphoneos</string>
```

**Comment by kirb** [comment]
Oh interesting, so only CydiaSubstrate was using `iphoneos`. Probably just a mistake considering everything else seems like it was working with Xcode 7 totally fine.

**Comment by elihwyma** [comment]
Does that mean that iOS does work in Xcode 7, or has nobody cared enough to try

**Pull request merged**
