### PR TITLE
Fix platform in CydiaSubstrate.tbd

### PR DESCRIPTION
**Pull request by captinc**

### CODE REVIEW

**Comment by kabiroberai** [comment]
I've already resolved this on a branch, see #9. Not sure whether duplicate commits are a good idea so I could cherry-pick that one onto master.

**Comment by NSExceptional** [comment]
@kabiroberai Is anything stopping you from cherry-picking it? cc @kirb

Trying to get my Theos setup "clean" and this is one of the few changes I still have to have locally

**Comment by kabiroberai** [comment]
Just busy rn, if someone else wants to cherry-pick from Orion and PR (or push to master if they have write access), feel free

**Comment by kabiroberai** [comment]
Nevermind, done: 8b7f487ee82d6a1357432ab2599f617ce8e5a82e

**Pull request closed without merging**
