### PR TITLE
Add oldabi libroot .a files, update libroot

### PR DESCRIPTION
**Pull request by opa334**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Adds oldabi libroot .a files, these have old arm64e ABI slices so they can be used by theos when compiling with old abi.
This also updates it to a version with the following changes:
- Make loading the provider actually work (critical)
- Don't redirect /var/mobile on XinaA15 v1

### CODE REVIEW

**Review by leptos-null — COMMENTED** [review]
v1 ABI looks good (tested with Xcode 15.3 and Xcode 13.2.1). I haven't tested on "oldABI".
May someone test on Xcode 12 and latest Linux toolchain?

**Comment by opa334** [comment]
> I haven't tested on "oldABI".

What do you mean by that?

All issues that could arise from this change could happen during compilation, the resulting tweak does not have to be tested at runtime.

Just test
Compiling rootful with Xcode 11
Compiling rootful with Xcode 15
Compiling rootless with Xcode 11
Compiling rootful with Xcode 15

I have tested all of these and everything is fine, I did not test on Linux however. I don't think this has to be tested on Xcode 14 - 12 as there shouldn't be any difference to Xcode 15.

**Comment by leptos-null** [comment]
> What do you mean by that?

I just meant a toolchain that compiles for "oldABI" (i.e. CPU subtype 2, no ABI mask).

I mistakenly thought Xcode 12 was the last version to use the old ABI, thanks.

Thanks for testing.

**Review by L1ghtmann — APPROVED** [review]
While I can't replicate the previously mentioned discrepancies between an old toolchain and the newer abi build on Linux, which seems to have been outright rejected by the older `ld` on OSX, both the oldabi and newabi builds successfully link on Linux and have been tested on OSX by Opa.

**Review by leptos-null — APPROVED** [review]
re-tested latest on macOS

**Comment by L1ghtmann** [comment]
Pending further discussion regarding Theos' handling of the different ABIs.

**Comment by leptos-null** [comment]
Per discussion, we'll merge this now due to the critical request of the PR.
Follow-up PR if needed to handle ABI versions.

**Pull request merged**
